//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the optitrack_xtion_sync package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __optitrack_xtion_sync__OPTITRACKXTIONSYNCCONFIG_H__
#define __optitrack_xtion_sync__OPTITRACKXTIONSYNCCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace optitrack_xtion_sync
{
  class OptiTrackXtionSyncConfigStatics;
  
  class OptiTrackXtionSyncConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(OptiTrackXtionSyncConfig &config, const OptiTrackXtionSyncConfig &max, const OptiTrackXtionSyncConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const OptiTrackXtionSyncConfig &config1, const OptiTrackXtionSyncConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, OptiTrackXtionSyncConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const OptiTrackXtionSyncConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, OptiTrackXtionSyncConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const OptiTrackXtionSyncConfig &config) const = 0;
      virtual void getValue(const OptiTrackXtionSyncConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T OptiTrackXtionSyncConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (OptiTrackXtionSyncConfig::* field);

      virtual void clamp(OptiTrackXtionSyncConfig &config, const OptiTrackXtionSyncConfig &max, const OptiTrackXtionSyncConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const OptiTrackXtionSyncConfig &config1, const OptiTrackXtionSyncConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, OptiTrackXtionSyncConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const OptiTrackXtionSyncConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, OptiTrackXtionSyncConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const OptiTrackXtionSyncConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const OptiTrackXtionSyncConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, OptiTrackXtionSyncConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, OptiTrackXtionSyncConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<OptiTrackXtionSyncConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(OptiTrackXtionSyncConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("quaternion_x"==(*_i)->name){quaternion_x = boost::any_cast<double>(val);}
        if("quaternion_y"==(*_i)->name){quaternion_y = boost::any_cast<double>(val);}
        if("quaternion_z"==(*_i)->name){quaternion_z = boost::any_cast<double>(val);}
        if("quaternion_w"==(*_i)->name){quaternion_w = boost::any_cast<double>(val);}
        if("translation_x"==(*_i)->name){translation_x = boost::any_cast<double>(val);}
        if("translation_y"==(*_i)->name){translation_y = boost::any_cast<double>(val);}
        if("translation_z"==(*_i)->name){translation_z = boost::any_cast<double>(val);}
      }
    }

    double quaternion_x;
double quaternion_y;
double quaternion_z;
double quaternion_w;
double translation_x;
double translation_y;
double translation_z;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double quaternion_x;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double quaternion_y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double quaternion_z;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double quaternion_w;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double translation_x;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double translation_y;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double translation_z;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("OptiTrackXtionSyncConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const OptiTrackXtionSyncConfig &__max__ = __getMax__();
      const OptiTrackXtionSyncConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const OptiTrackXtionSyncConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const OptiTrackXtionSyncConfig &__getDefault__();
    static const OptiTrackXtionSyncConfig &__getMax__();
    static const OptiTrackXtionSyncConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const OptiTrackXtionSyncConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void OptiTrackXtionSyncConfig::ParamDescription<std::string>::clamp(OptiTrackXtionSyncConfig &config, const OptiTrackXtionSyncConfig &max, const OptiTrackXtionSyncConfig &min) const
  {
    return;
  }

  class OptiTrackXtionSyncConfigStatics
  {
    friend class OptiTrackXtionSyncConfig;
    
    OptiTrackXtionSyncConfigStatics()
    {
OptiTrackXtionSyncConfig::GroupDescription<OptiTrackXtionSyncConfig::DEFAULT, OptiTrackXtionSyncConfig> Default("Default", "", 0, 0, true, &OptiTrackXtionSyncConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.quaternion_x = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.quaternion_x = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.quaternion_x = -0.045;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("quaternion_x", "double", 0, "quaternion x", "", &OptiTrackXtionSyncConfig::quaternion_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("quaternion_x", "double", 0, "quaternion x", "", &OptiTrackXtionSyncConfig::quaternion_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.quaternion_y = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.quaternion_y = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.quaternion_y = 0.16;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("quaternion_y", "double", 0, "quaternion y", "", &OptiTrackXtionSyncConfig::quaternion_y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("quaternion_y", "double", 0, "quaternion y", "", &OptiTrackXtionSyncConfig::quaternion_y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.quaternion_z = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.quaternion_z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.quaternion_z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("quaternion_z", "double", 0, "quaternion z", "", &OptiTrackXtionSyncConfig::quaternion_z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("quaternion_z", "double", 0, "quaternion z", "", &OptiTrackXtionSyncConfig::quaternion_z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.quaternion_w = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.quaternion_w = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.quaternion_w = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("quaternion_w", "double", 0, "quaternion w", "", &OptiTrackXtionSyncConfig::quaternion_w)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("quaternion_w", "double", 0, "quaternion w", "", &OptiTrackXtionSyncConfig::quaternion_w)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.translation_x = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.translation_x = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.translation_x = -0.08;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("translation_x", "double", 0, "translation x", "", &OptiTrackXtionSyncConfig::translation_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("translation_x", "double", 0, "translation x", "", &OptiTrackXtionSyncConfig::translation_x)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.translation_y = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.translation_y = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.translation_y = -0.03;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("translation_y", "double", 0, "translation y", "", &OptiTrackXtionSyncConfig::translation_y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("translation_y", "double", 0, "translation y", "", &OptiTrackXtionSyncConfig::translation_y)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.translation_z = -1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.translation_z = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.translation_z = -0.02;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("translation_z", "double", 0, "translation z", "", &OptiTrackXtionSyncConfig::translation_z)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr(new OptiTrackXtionSyncConfig::ParamDescription<double>("translation_z", "double", 0, "translation z", "", &OptiTrackXtionSyncConfig::translation_z)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(OptiTrackXtionSyncConfig::AbstractGroupDescriptionConstPtr(new OptiTrackXtionSyncConfig::GroupDescription<OptiTrackXtionSyncConfig::DEFAULT, OptiTrackXtionSyncConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<OptiTrackXtionSyncConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<OptiTrackXtionSyncConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    OptiTrackXtionSyncConfig __max__;
    OptiTrackXtionSyncConfig __min__;
    OptiTrackXtionSyncConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const OptiTrackXtionSyncConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static OptiTrackXtionSyncConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &OptiTrackXtionSyncConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const OptiTrackXtionSyncConfig &OptiTrackXtionSyncConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const OptiTrackXtionSyncConfig &OptiTrackXtionSyncConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const OptiTrackXtionSyncConfig &OptiTrackXtionSyncConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<OptiTrackXtionSyncConfig::AbstractParamDescriptionConstPtr> &OptiTrackXtionSyncConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<OptiTrackXtionSyncConfig::AbstractGroupDescriptionConstPtr> &OptiTrackXtionSyncConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const OptiTrackXtionSyncConfigStatics *OptiTrackXtionSyncConfig::__get_statics__()
  {
    const static OptiTrackXtionSyncConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = OptiTrackXtionSyncConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __OPTITRACKXTIONSYNCRECONFIGURATOR_H__
